#!/bin/bash

cd /home/drew/sites/officeatlas.com/current
git pull origin master
rm config.coffee
ln -s ../config.coffee config.coffee
touch officeatlas.coffee

# to set up nginx
# see office.the.tl example
# needs to be in /etc/nginx/sites-enabled (at least sym linked)
